import { findBlock, replaceScalarField, replaceArrayField } from './table-source.ts';
import { formatNumberLiteral } from './format.ts';

export interface PatchPlan {
  readonly exportName: string;
  readonly bySize?: readonly number[];
  readonly perAdditionalPerson?: number;
  readonly fourPersonMedian?: number;
  readonly effectiveYear: number;
  readonly source: string;
  /** Full `/** ... *\/` block (no leading/trailing newline) inserted directly above the export. */
  readonly proposedComment: string;
}

/**
 * Apply one table's proposed update to the full file text. Never touches any other
 * export's block, and never removes or rewrites the export's existing hand-written JSDoc --
 * it only inserts a new comment above it and edits the data fields inside the object
 * literal. This is what keeps an untouched table byte-for-byte identical in the diff.
 */
export function applyPatch(fileText: string, plan: PatchPlan): string {
  const { blockStart, braceOpen, braceClose, blockEnd, body } = findBlock(fileText, plan.exportName);

  let newBody = body;
  if (plan.bySize) {
    newBody = replaceArrayField(newBody, plan.exportName, 'bySize', plan.bySize.map(formatNumberLiteral).join(', '));
  }
  if (plan.perAdditionalPerson !== undefined) {
    newBody = replaceScalarField(
      newBody,
      plan.exportName,
      'perAdditionalPerson',
      formatNumberLiteral(plan.perAdditionalPerson),
    );
  }
  if (plan.fourPersonMedian !== undefined) {
    newBody = replaceScalarField(
      newBody,
      plan.exportName,
      'fourPersonMedian',
      formatNumberLiteral(plan.fourPersonMedian),
    );
  }
  newBody = replaceScalarField(newBody, plan.exportName, 'effectiveYear', String(plan.effectiveYear));
  newBody = replaceScalarField(newBody, plan.exportName, 'source', `'${plan.source}'`);
  // Never written as true by this script -- a human confirms and flips this by hand.
  newBody = replaceScalarField(newBody, plan.exportName, 'verified', 'false');
  newBody = replaceScalarField(newBody, plan.exportName, 'lastVerified', 'null');

  const prefix = fileText.slice(0, blockStart);
  const declarationPrefix = fileText.slice(blockStart, braceOpen);
  const suffix = fileText.slice(braceClose + 1, blockEnd);
  const rest = fileText.slice(blockEnd);

  return `${prefix}\n${plan.proposedComment}\n${declarationPrefix}${newBody}${suffix}${rest}`;
}

export function buildProposedComment(params: {
  readonly generatedAt: string; // ISO date
  readonly summaryLines: readonly string[];
  readonly provenance: readonly string[];
}): string {
  const lines = [
    '/**',
    ` * PROPOSED UPDATE (unverified) -- generated by scripts/refresh-income-tables on ${params.generatedAt}.`,
    ' * This paragraph was written by a script, not a person -- verified is set to false and',
    ' * lastVerified to null until a human checks the figures below against the source and',
    ' * confirms them (see docs/data-authoring.md, "Reviewing a proposed update").',
    ' *',
    ...params.summaryLines.map((l) => ` * ${l}`),
    ' *',
    ' * Sources consulted:',
    ...params.provenance.map((p) => ` * - ${p}`),
    ' */',
  ];
  return lines.join('\n');
}
