import { FACT_KEYS } from '../../src/domain/facts.ts';

/**
 * JSON Schema for `Criterion` (src/domain/criteria.ts), built from `FACT_KEYS`
 * rather than hand-copied -- so the schema handed to the model can never drift
 * from the actual fact vocabulary the way a maintained-by-hand copy could.
 *
 * Used as a forced tool-use schema on the extraction call: the model can only
 * construct `Criterion` node shapes, and any `fact` reference it uses must be
 * one of the real declared facts. This does NOT by itself guarantee the
 * *values* compared against enum facts are valid (JSON Schema can constrain
 * `fact` to a known key, but not "the value must be one of *that specific
 * fact's* options" -- a cross-field constraint JSON Schema can't express).
 * That's exactly why schema-gate.ts exists as a second, post-hoc check: the
 * tool schema keeps the model in the right neighborhood, and schema-gate.ts is
 * the ground truth the way tests/data/vocabulary.test.ts is for the
 * hand-authored dataset.
 *
 * ## Why the schema is depth-bounded rather than recursive (issue #23)
 *
 * `Criterion` is genuinely recursive -- allOf/anyOf/not contain criteria -- so
 * the obvious encoding is a `$defs.criterion` that `$ref`s itself. That is
 * valid JSON Schema and it is what this file did originally. The API rejects
 * it outright:
 *
 *   HTTP 400 invalid_request_error
 *   tools.0.custom: Invalid schema: Circular reference detected in schema
 *   definitions: criterion -> criterion. Self-referencing or
 *   mutually-referencing definitions are not supported.
 *
 * Every one of the nine eval cases failed this way on the first live run, which
 * is why #5's harness had never actually scored anything.
 *
 * The fix is to inline the tree to a fixed depth instead of referencing it.
 * Leaves are allowed at every level; combinators are allowed until the budget
 * runs out, and at depth 0 only leaves remain. Real rules are shallow --
 * `allOf(livesIn.wisconsin, anyOf(incomeAtOrBelow(...), hasAnyOf(...)))` is the
 * deepest shape in the hand-authored dataset at depth 2 -- so depth 3 leaves
 * headroom without the schema exploding in size.
 *
 * A rule too deep for the budget cannot be emitted at all, which fails in the
 * safe direction: the model is pushed toward `manualReview` rather than toward
 * a subtly wrong flattening of a rule it could not express.
 *
 * ## Why there is no optional `label` (also issue #23)
 *
 * Two further limits surfaced on live runs, in order:
 *
 *   tools.0.custom: Schema type 'oneOf' is not supported
 *   Schemas contains too many optional parameters (239) ... (limit: 24)
 *
 * The first is why every branch uses `anyOf`. The second is why `Criterion`'s
 * optional `label` is absent here: it is optional on every node kind, and
 * inlining to depth 3 multiplies it into hundreds of optional parameters.
 *
 * Dropping it costs nothing, and is what the design wanted anyway. Per
 * docs/design.md, explanations are *generated by walking the evaluated tree*,
 * precisely so they cannot go stale when a neighbouring rule changes. A
 * model-authored label would reintroduce the hand-written prose that design
 * exists to avoid. `label` stays in the TypeScript type for hand-authored
 * records; extraction simply never emits one.
 *
 * With `label` gone, every remaining property is required, so the optional
 * count is zero and the depth budget is bounded only by schema size.
 */

const FACT_KEY_SCHEMA = { type: 'string', enum: [...FACT_KEYS] } as const;

const VALUE_SCHEMA = {
  anyOf: [{ type: 'number' }, { type: 'string' }, { type: 'boolean' }],
  description:
    'For a string value against an enum fact, this must be one of that fact\'s exact declared slugs -- see the ENUM FACT VALUES list in the system prompt. JSON Schema cannot enforce this cross-field constraint; schema-gate.ts rejects a wrong slug after the fact.',
} as const;

/** Node kinds with no child criteria -- legal at any depth, including 0. */
const LEAF_SCHEMAS = [
  {
    type: 'object',
    properties: { kind: { const: 'always' } },
    required: ['kind'],
    additionalProperties: false,
  },
  {
    type: 'object',
    properties: {
      kind: { const: 'manualReview' },
      note: {
        type: 'string',
        description:
          'Plain-language reason a human needs to check this by hand -- e.g. "subject to funding availability", "waitlist status varies", "immigration-status exceptions apply".',
      },
    },
    required: ['kind', 'note'],
    additionalProperties: false,
  },
  {
    type: 'object',
    properties: {
      kind: { const: 'compare' },
      fact: FACT_KEY_SCHEMA,
      op: { enum: ['eq', 'neq', 'lt', 'lte', 'gt', 'gte'] },
      value: VALUE_SCHEMA,
    },
    required: ['kind', 'fact', 'op', 'value'],
    additionalProperties: false,
  },
  {
    type: 'object',
    properties: {
      kind: { const: 'set' },
      fact: FACT_KEY_SCHEMA,
      op: { enum: ['in', 'notIn', 'includesAny', 'includesAll', 'excludes'] },
      values: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Each entry must be one of the referenced fact\'s exact declared slugs (see the ENUM FACT VALUES list in the system prompt) -- never a display name or source phrase. Drop any program the source names that has no slug; do not invent one.',
      },
    },
    required: ['kind', 'fact', 'op', 'values'],
    additionalProperties: false,
  },
  {
    type: 'object',
    properties: {
      kind: { const: 'incomeAtOrBelow' },
      scale: { enum: ['fpl', 'wi-smi', 'dane-ami'] },
      percent: { type: 'number' },
    },
    required: ['kind', 'scale', 'percent'],
    additionalProperties: false,
  },
] as const;

/** allOf/anyOf/not, with their children pinned to an already-built schema. */
function combinatorSchemas(child: object) {
  return [
    {
      type: 'object',
      properties: {
        kind: { const: 'allOf' },
        of: { type: 'array', items: child, minItems: 1 },
      },
      required: ['kind', 'of'],
      additionalProperties: false,
    },
    {
      type: 'object',
      properties: {
        kind: { const: 'anyOf' },
        of: { type: 'array', items: child, minItems: 1 },
      },
      required: ['kind', 'of'],
      additionalProperties: false,
    },
    {
      type: 'object',
      properties: {
        kind: { const: 'not' },
        of: child,
      },
      required: ['kind', 'of'],
      additionalProperties: false,
    },
  ];
}

/** Inlines the criterion tree to `depth` levels of nesting. No `$ref`. */
function criterionAtDepth(depth: number): { anyOf: object[] } {
  if (depth <= 0) return { anyOf: [...LEAF_SCHEMAS] };
  return { anyOf: [...LEAF_SCHEMAS, ...combinatorSchemas(criterionAtDepth(depth - 1))] };
}

export const DEFAULT_MAX_DEPTH = 3;

export function buildCriterionJsonSchema(maxDepth: number = DEFAULT_MAX_DEPTH) {
  return {
    type: 'object',
    properties: {
      criterion: {
        ...criterionAtDepth(maxDepth),
        description:
          'The extracted eligibility rule. Use manualReview (possibly nested inside allOf alongside real compare/incomeAtOrBelow/set criteria) for any condition you cannot express precisely and confidently -- do not guess a threshold or enumerate an exception list you are not certain is complete.',
      },
      sourceExcerpt: {
        type: 'string',
        description:
          'The exact span of the supplied excerpt this rule was derived from, quoted verbatim. Must appear in the excerpt.',
      },
      confidence: {
        enum: ['high', 'low'],
        description:
          'low whenever you are not highly confident, even if you produced a specific rule rather than manualReview.',
      },
    },
    required: ['criterion', 'sourceExcerpt', 'confidence'],
    additionalProperties: false,
  };
}
