/**
 * Read/write scripts/check-sources/source-hashes.json -- the committed baseline
 * #7 asks for ("a committed file, not an opaque blob", so a change is diffable
 * in review).
 *
 * One entry per program id. Kept sorted by id and pretty-printed with a stable
 * key order so a real content change shows up as a one- or two-line diff and
 * nothing else moves. The file lives next to this script rather than in
 * src/data/ because src/data/programs/*.ts is off-limits to automation and
 * nothing in the browser bundle should import a hash log.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const HASHES_PATH = fileURLToPath(new URL('../source-hashes.json', import.meta.url));

export type SourceStatus = 'ok' | 'gone' | 'unreachable';

export interface SourceHashEntry {
  /** The `source.url` this hash was taken from, copied in so the file reads standalone. */
  readonly url: string;
  /** `sha256:<hex>` of the normalized text, or null when the last fetch failed. */
  readonly normalizedSha256: string | null;
  /** Length of the normalized text in characters -- a cheap "how much changed" hint. */
  readonly normalizedChars: number | null;
  /** Outcome of the most recent fetch that produced a write. */
  readonly status: SourceStatus;
  /** ISO date (YYYY-MM-DD) this entry was first recorded. */
  readonly firstSeen: string;
  /** ISO date (YYYY-MM-DD) the normalized text last changed. */
  readonly lastChanged: string;
  /**
   * Count of back-to-back runs that failed to fetch this source (timeout / 403 /
   * 5xx / network error). Reset to 0 -- and omitted from the serialized file --
   * the moment a fetch succeeds or the page 404s. A single failure is almost
   * always a blip at 17 monthly sources, so `unreachable` only becomes an
   * actionable, PR-opening finding once this reaches
   * `check.ts`'s ESCALATE_AFTER_FAILURES. A 404/410 is `gone`, not
   * `unreachable`, and never touches this counter -- it escalates on the first
   * run. See issue #49.
   */
  readonly consecutiveFailures?: number;
}

/*
 * There is deliberately no `lastChecked` field. If every run stamped "checked
 * today", the file would diff on every scheduled run and a PR would open every
 * month regardless of whether anything changed -- the opposite of "unchanged
 * records are silent". Every field here moves only on a real event, so an
 * unchanged run reproduces the file byte-for-byte. "Did the job run?" is
 * answered by the workflow's run history, not by this file.
 */

export interface HashesFile {
  readonly $schema: string;
  readonly generatedBy: string;
  readonly sources: Record<string, SourceHashEntry>;
}

const HEADER = {
  $schema:
    'Generated by `npm run check:sources`. One entry per program id. Do not hand-edit hashes; do fix a `url` here if you fix it in the program record.',
  generatedBy: 'scripts/check-sources',
} as const;

export function sha256(text: string): string {
  return `sha256:${createHash('sha256').update(text, 'utf8').digest('hex')}`;
}

export function emptyHashesFile(): HashesFile {
  return { ...HEADER, sources: {} };
}

export function readHashesFile(path: string = HASHES_PATH): HashesFile {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch {
    return emptyHashesFile();
  }
  const parsed = JSON.parse(raw) as Partial<HashesFile>;
  return { ...HEADER, sources: parsed.sources ?? {} };
}

/** Serialize with sorted ids and a fixed key order, newline-terminated. */
export function serializeHashesFile(file: HashesFile): string {
  const sortedSources: Record<string, SourceHashEntry> = {};
  for (const id of Object.keys(file.sources).sort()) {
    const e = file.sources[id];
    if (!e) continue;
    sortedSources[id] = {
      url: e.url,
      normalizedSha256: e.normalizedSha256,
      normalizedChars: e.normalizedChars,
      status: e.status,
      firstSeen: e.firstSeen,
      lastChanged: e.lastChanged,
      // Only written while a source is actively failing, so an all-healthy run
      // reproduces the file byte-for-byte (issue #49's fixed-point constraint).
      ...(e.consecutiveFailures && e.consecutiveFailures > 0
        ? { consecutiveFailures: e.consecutiveFailures }
        : {}),
    };
  }
  return `${JSON.stringify({ ...HEADER, sources: sortedSources }, null, 2)}\n`;
}

export function writeHashesFile(file: HashesFile, path: string = HASHES_PATH): void {
  writeFileSync(path, serializeHashesFile(file), 'utf8');
}
